export const verifyInputJsonSchema = {
  type: "object",
  properties: {
    company_name: {
      type: "string",
      minLength: 2,
      maxLength: 200,
      description: "Israeli company legal or trading name",
    },
    company_number: {
      type: "string",
      minLength: 1,
      maxLength: 30,
      description: "Israeli company number",
    },
    website: {
      type: "string",
      format: "uri",
      description: "Optional company website",
    },
    language: { type: "string", enum: ["en", "he"], default: "en" },
    city: {
      type: "string",
      description: "Optional city used to disambiguate a company name",
    },
    expected_entity_type: {
      type: "string",
      description:
        "Optional expected legal entity type used for disambiguation",
    },
    depth: { type: "string", enum: ["basic", "standard"], default: "standard" },
  },
  anyOf: [{ required: ["company_name"] }, { required: ["company_number"] }],
  additionalProperties: false,
} as const;

export const verifyOutputJsonSchema = {
  type: "object",
  properties: {
    request_id: { type: "string", format: "uuid" },
    api_version: { type: "string" },
    query: { type: "object" },
    resolution_status: {
      type: "string",
      enum: ["RESOLVED", "AMBIGUOUS", "NOT_FOUND"],
    },
    resolved_entity: { type: ["object", "null"] },
    candidates: { type: "array", items: { type: "object" } },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    summary: { type: ["string", "null"] },
    evidence: { type: "array", items: { type: "object" } },
    missing_data: { type: "array", items: { type: "string" } },
    checked_at: { type: "string", format: "date-time" },
  },
  required: [
    "request_id",
    "api_version",
    "query",
    "resolution_status",
    "resolved_entity",
    "candidates",
    "confidence",
    "summary",
    "evidence",
    "missing_data",
    "checked_at",
  ],
  additionalProperties: false,
} as const;

export const verifyExample = {
  request_id: "2a1cb5df-4078-4cb2-8eda-8f1ff6f21f2d",
  api_version: "1.0.0",
  query: { company_number: "514744887", language: "en", depth: "standard" },
  resolution_status: "RESOLVED",
  resolved_entity: {
    legal_name: "מנדיי. קום בע״מ",
    english_name: "MONDAY.COM LTD",
    company_number: "514744887",
    entity_type: "ישראלית חברה ציבורית",
    status: "פעילה",
    registered_address: {
      city: "תל אביב - יפו",
      street: "יצחק שדה",
      house_number: "6",
      postal_code: "6777506",
      country: "ישראל",
    },
    incorporation_date: "13/03/2012",
    law_violation_flag: false,
    latest_annual_report_year: 2025,
  },
  candidates: [],
  confidence: 0.99,
  summary: "מנדיי. קום בע״מ (514744887) is registered with status פעילה.",
  evidence: [
    {
      field: "company_number",
      value: "514744887",
      type: "fact",
      source: "Israeli Companies Registry open dataset",
      source_url: "https://data.gov.il/dataset/ica_companies",
      retrieved_at: "2026-08-27T00:00:00.000Z",
      source_record_id: "sample-514744887",
      confidence: 0.99,
    },
    {
      field: "company_status",
      value: "פעילה",
      type: "fact",
      source: "Israeli Companies Registry open dataset",
      source_url: "https://data.gov.il/dataset/ica_companies",
      retrieved_at: "2026-08-27T00:00:00.000Z",
      source_record_id: "sample-514744887",
      confidence: 0.99,
    },
    {
      field: "registered_address",
      value: {
        city: "תל אביב - יפו",
        street: "יצחק שדה",
        house_number: "6",
        postal_code: "6777506",
        country: "ישראל",
      },
      type: "fact",
      source: "Israeli Companies Registry open dataset",
      source_url: "https://data.gov.il/dataset/ica_companies",
      retrieved_at: "2026-08-27T00:00:00.000Z",
      source_record_id: "sample-514744887",
      confidence: 0.99,
    },
  ],
  missing_data: [],
  checked_at: "2026-08-27T00:00:00.000Z",
} as const;
